### ISSUE TITLE
sensorsディレクトリについて

### ISSUE THREAD

**Issue by yuma300** [Lemmings/lemmings-ripple#5]
sensorsディレクトリはリポジトリに入れておかないのですか？

**Comment by you21979** [comment]
sensorsも場当たり的に作ってしまってまだ概念を消化しきってないんです。
おそらく仕組み上agentsでいいじゃんと思われたかもしれないですが
agentsですべて解決してしまうと初期化の優先順位が決められないので
sensorsは初期化の優先順位を解決するために作られました。（センサーはエージェントより早く初期化したい）
いま本当にそれでいいのか考えてるところです。（が最近いじってないので放置されてます）

**Comment by you21979** [comment]
unixのrc3.dの中みたいにファイル名に起動順を入れるというのも有りかもと思ったり。
ただ順番を解決しても非同期に初期化するものはあまり解決になってないんですよね。ちゃんと待たないと。そういう意味で概念として考えてます。

**Comment by you21979** [comment]
現行のバージョンには追加します
